### ISSUE TITLE
Dependencies not installed with setup.py (or distutils insufficient)

### ISSUE THREAD

**Issue by klauer** [epicsdeb/pypdb#2]
Dependencies do not install via `pip install` or `setup.py install` as the standard library module `distutils` doesn't handle `requires` in the way one might expect.

https://github.com/epicsdeb/pypdb/blob/9da3cf9648676cd01859a3197dd67b7fefaf81dd/setup.py#L18

Making `setuptools` a requirement and changing the above to `install_requires` should be sufficient.

Would you object to a PR changing the above, @mdavidsaver? We're looking to make pypdb a runtime dependency of pytmc, so I'm trying to sort out the packaging.

cc @teddyrendahl @n-wbrown @zllentz

**Comment by mdavidsaver** [comment]
> Making `setuptools` a requirement and changing the above to `install_requires` should be sufficient.

Sure.  I've made my peace with setuptools since 2011.

> We're looking to make pypdb a runtime dependency of pytmc

What interface are you looking at?  CLI or API?

**Comment by klauer** [comment]
Great! I'll submit a PR today.

Usage will be a mix of API (what fields, record types, DTYPs are available in a dbd?) and CLI (the linter - already used currently in our package testing, but will likely be refactored).
